### ISSUE TITLE
Validator Rules: railway:signal*=* Without railway=signal

### ISSUE THREAD

**Issue by Nakaner** [rurseekatze/OpenRailwayMap#106]
Quote from Dakon from #OpenRailwayMap IRC:
> Reported by ich fände es toll wenn JOSM die 2 Fehler, die ich in der letzten Woche gemacht habe, 
> anmeckern würde:
>   -railway:signal* ohne railway=signal
>   -railway=signal nicht auf den Schienen, sondern daneben

In English:
* JOSM should warn if a node has railway:signal:*=* but no railway=signal.
* JOSM should warn if a node has railway=signal but is not part of a track.

**Comment by rurseekatze** [comment]
A rule for detecting the first problem (railway:signal:= but no railway=signal) was added with #119.

It seems that the second problem cannot be detected yet, as the MapCSS validation rules can currently just check tagging problems, but not geometry problems.

**Comment by rurseekatze** [comment]
Fixed by #500.
