### ISSUE TITLE
Use abandoned:name to render the name of razed tracks.

### ISSUE THREAD

**Issue by ViriatoLusitano** [rurseekatze/OpenRailwayMap#114]
This is a suggestion first and foremost. 

There are instances where a track was demolished and a new feature was built upon it. Take [this example](http://www.openstreetmap.org/way/325552701) where a cycleway follows the razed railway line. 

What happens is that the name of the new feature appears on the renderer [instead of the name of the track that was razed](http://www.openrailwaymap.org/?lang=en&lat=42.0291740276681&lon=-8.635864108800888&zoom=19&style=standard).

There's also the tag [old_name](http://taginfo.openstreetmap.org/keys/old_name#overview) which is a lot more used than [abandoned:name](http://taginfo.openstreetmap.org/keys/abandoned%3Aname#overview).

**Comment by rurseekatze** [comment]
Support for `abandoned:name` `abandoned:ref`, `razed:name` and `razed:ref` was merged into the style.

The example you have linked above is not rendered correctly yet due to wrong tagging. You should change `railway=razed` to `railway=abandoned` for a consistent tagging.
