### ISSUE TITLE
Only render white tunnel halo if the feature is rendered

### ISSUE THREAD

**Issue by Nakaner** [rurseekatze/OpenRailwayMap#160]
At the moment a white halo is rendered around every feature in the database which is tagged tunnel=yes. This applies e.g. for railway=platform ([example](http://www.openrailwaymap.org/?lang=de&lat=50.94184404496653&lon=6.958064585924149&zoom=19&style=standard)). There are two solutions:

1. Add `[railway=rail]`, `[railway=tram]` etc. to the selector rule.
2. Render also `railway=platform`.

**Comment by rurseekatze** [comment]
Was fixed by #219.
