### ISSUE TITLE
Railroad is invisible 

### ISSUE THREAD

**Issue by Michael21011** [rurseekatze/OpenRailwayMap#175]
Hi.
I found that one piece of railroad is invisible on map 
http://www.openrailwaymap.org/?lang=en&lat=53.85594388961122&lon=27.505388259887695&zoom=14&style=standard
![railinvisible](https://cloud.githubusercontent.com/assets/9266780/6867072/5289ab7e-d48f-11e4-8796-30a6e54d55b3.png)
Could you check if there are wrong tags or OpenRailwayMap bug, please?

__List of tags on visible railroad:__
electrified=contact_line
frequency=50
railway=rail
tracks=1
usage=main
voltage=25000

__List of tags on invisible railroad 1:__
electrified=contact_line
frequency=50
gauge=1520
railway=rail
service=main
tracks=2
usage=main
voltage=25000

__List of tags on invisible railroad 2:__
electrified=contact_line
frequency=50
railway=rail
service=main
tracks=1
usage=industrial
voltage=25000

Thanks in advance!

**Comment by Nakaner** [comment]
It is wrong tagging.

Invisible railroad 1:
`usage=main` + `service=main` is wrong tagging. Every way must either have `usage=main/branch/industrial/military/test` or `service=siding/yard/spur/crossover`. You may only tag both `usage=*` and `service=*` if the track is an industrial railway line (`usage=industrial`) or military railway line (`usage=military`).

Invisible railroad 2:
`service=main` is wrong tagging. You can only use one of the following `service=*´ values: `siding`, `yard`, `spur` and `crossover`.

Our JOSM validator rules would report this. ([source code](https://github.com/rurseekatze/OpenRailwayMap/blob/master/validator/openrailwaymap.validator.mapcss), [download](http://www.openrailwaymap.org/validator/openrailwaymap.validator.mapcss)

**Comment by rurseekatze** [comment]
Tagging issues seem to be fixed.
