### ISSUE TITLE
Possible track render bug

### ISSUE THREAD

**Issue by JJJWegdam** [rurseekatze/OpenRailwayMap#178]
Sometimes horizontal and vertical lines appear at higher zoom levels.
![Alt Text](http://puu.sh/gZ0LU/b33aef6311.PNG)
Example between Amsterdam and Leiden

**Comment by rurseekatze** [comment]
This is a known bug of the used rendering software https://github.com/rurseekatze/node-tileserver . There is already a bug in that repository, so I close this issue: https://github.com/rurseekatze/node-tileserver/issues/11
