### ISSUE TITLE
Rendering of Sv signals with Sh signal

### ISSUE THREAD

**Issue by Nakaner** [rurseekatze/OpenRailwayMap#193]
There are a lot of Sv signals in Hamburg which also have a Sh minor signal mounted below the Sv signal at the same pole. Due to a bug in the style sheet the Sh signal is rendered, not the Sv signal.

**Comment by Nakaner** [comment]
The same problem also exists if a whistle sign and a Hp semaphore signal share the pole.

**Comment by Nakaner** [comment]
The problem is not as easy solveable as I toughed. The z-index between Sh and Sv signals already differs about 4000 to 5000 units. Moving Sv signals to as separate layer might works not well because the Sh icon is wider.

**Comment by rurseekatze** [comment]
The reordered stylesheet was merged and deployed on the server. Do you have any examples to check if the changes work as expected in KothicJS?

**Comment by Nakaner** [comment]
> Do you have any examples to check if the changes work as expected in KothicJS?

Just have a look at Sv signals at stations, e.g. [Hamburg Berliner Tor](http://www.openrailwaymap.org/canvas.php?lang=de&lat=53.55250073098687&lon=10.02493992447853&zoom=19&style=signals). Signals 84, 641 and 802 should be rendered as Sv signals, not as Sh signals.

It is correct that you have closed this issue.
