### ISSUE TITLE
Rendering of worse tagged signals

### ISSUE THREAD

**Issue by Nakaner** [rurseekatze/OpenRailwayMap#194]
If a Hp signal is tagged `railway:signal:main:states=DE-ESO:hp0` a Hp 1 icon is rendered. That should not happen, Hp 0 should be rendered.

**Comment by DerDakon** [comment]
The same problem exists at least for Vr signals.

**Comment by rurseekatze** [comment]
Both rendering issues were fixed, so this issue can be closed.
