### ISSUE TITLE
Add `railway:signal:distant:shortened=*` to Hl distant signal preset

### ISSUE THREAD

**Issue by Nakaner** [rurseekatze/OpenRailwayMap#196]
Add `railway:signal:distant:shortened=*` to Hl distant signal preset. It is missing.

**Comment by DerDakon** [comment]
I don't see those mentioned in Rl301, section 301.0103.

**Comment by PeterDRS** [comment]
It does not exist.

**Comment by Nakaner** [comment]
@DerDakon wrote:
> I don't see those mentioned in Rl301, section 301.0103.

Just have a look at Ril 301, section 301.1401, paragraph 2.10:

> Zur Kennzeichnung des Standorts eines im verkürzten Abstand des Bremswegs der Strecke stehenden zweibegriffigen Formvorsignals oder Lichtvorsignals im Geltungsbereich der DV 301, das nicht gem. Modul 301.0201 Abschnitt 1 Absatz 14 mit einem weißen Zusatzlicht oder gem. Modul 301.1401 Abschnitt 2 Absatz 9 gekennzeichnet ist, kann eine schwarz geränderte, weiße Tafel mit zwei übereinander stehenden schwarzen Winkeln, deren Spitzen durch einen schwarzen Ring verdeckt sind, aufgestellt sein.

From my point of view, this means that there can be shortened Hl distant signals.

**Comment by PeterDRS** [comment]
A good argument to start rendering Ne 2. ;)
