### ISSUE TITLE
Overlay does not appear in IE10

### ISSUE THREAD

**Issue by rurseekatze** [rurseekatze/OpenRailwayMap#20]
The canvas overlay is not rendered in Internet Explorer 10.
It is supposed to be a bug in Kothic JS (https://github.com/kothic/kothic-js).

**Comment by bigbug21** [comment]
This also occurs in IE 11.

**Comment by bigbug21** [comment]
Since the recent Leaflet update, ORM works flawlessly on IE 11!

**Comment by rurseekatze** [comment]
:+1:
