### ISSUE TITLE
Proposal to render/tag catenary structures

### ISSUE THREAD

**Issue by JJJWegdam** [rurseekatze/OpenRailwayMap#215]
The Dutch datasets contain all catenary structures in the Netherlands. I thought it would be a nice opportunity for an automated import + render. Because of the goal of this page, I'll focus on the and rendering.
Catenary poles can currently be tagged as power=catenary_mast. I'd like to propose an additional power=catenary_fixture to tag catenary portals, stanchions and arms.
Also I'd like to propose to render both tags. A few weeks ago I tagged some catenaries for the Mapnik renderer (for a very limited timespan), to give you guys a view on how it would benefit to a map.

![enschede cs](https://cloud.githubusercontent.com/assets/11754036/7433615/8af8ed84-f033-11e4-8509-a16fd83c97ae.JPG)

Disclaimer: I realise that a tagging proposal should be in the mailing list. This time it is however a combination of a tagging and render proposal.

**Comment by rurseekatze** [comment]
This is a tagging discussion. Please continue it on the mailing list.

**Comment by JJJWegdam** [comment]
The Dutch public datasets (please consider attachment for more info) contain all catenary structures in the Netherlands. Since I found out that no catenary structures have yet been mapped anywhere in the country, I thought it would be a nice opportunity for an automated import.
Catenary poles (displayed as nodes in the datasets) can currently be tagged as power=catenary_mast. I'd like to propose an additional power=catenary_fixture tag to tag catenary portal-beams, stanchions and arms (displayed as lines in the datasets).
I'd appreciate to hear your opinion on this new tag. It would bring the import a step closer. Thank you in advance.

Jeroen Wegdam
Student-assistant at ProRail
(Dutch railway asset owner)

PS/update: currently, I am replacing all Dutch OSM railway ways with proper positions. Before importing the catenaries, I will first finish the railway geometry and platform wall imports. This will result in catenaries that fit seamlesssly to the railways. All imports are done manually (with great care for existing data).

Op 18 okt 2015 om 13:09 uur uur schreef Alexander Matheisen <notifications@github.com>:

This is a tagging discussion. Please continue it on the mailing list.
