### ISSUE TITLE
ORM won't move on IE9

### ISSUE THREAD

**Issue by bigbug21** [rurseekatze/OpenRailwayMap#239]
For some reason, OpenRailwayMap cannot properly be used on Internet Explorer 9, the standard web browser at Deutsche Bahn. It is not posible to move on the map, neither by mouse turns nor by arrow keys.

**Comment by rurseekatze** [comment]
Do other Leaflet maps (like the examples at http://leafletjs.com/examples.html) work? 

Are there any error messages in the web developer console?

**Comment by bigbug21** [comment]
There are indeed errors on the web developer console:
"SCRIPT5022: DOM Exception: SECURITY_ERR (18).
 L.TileLayer.Greyscale.js, Zeile 54 Zeichen 4"

Beside the non-working scrolling, there is also no default background.

As for the other leaflet maps, the first example at the first page already works fine (http://leafletjs.com/examples/quick-start.html).

**Comment by rurseekatze** [comment]
Seems to be the same or a similar problem as #35.

**Comment by Nakaner** [comment]
Ugly fix: Maybe show coloured Mapnik layer on IE and a note (should be avoided but seems necessary and simple) 
> Internet Explorer does not support a lightweight grayscale map. Sorry.
> We do not have the money to operate an own tiled map service which serves grayscaled map tiles.
> We suggest to use another browser like Firefox or Chrome.

We do not have the money to either operate our own grayscale TMS or a proxy which converts coloured tiles to grayscale.

**Comment by rurseekatze** [comment]
@bigbug21 Does http://zverik.github.io/leaflet-grayscale/ also not work and throws this error?
In this case this would be a bug in https://github.com/Zverik/leaflet-grayscale/, so I would close this issue because there is nothing to do for us and hope that the maintainer of the plugin fixes the issue.

**Comment by bigbug21** [comment]
@rurseekatze: While map is shown in colors on IE9, navigating it (zooming, moving) works fine.

**Comment by bigbug21** [comment]
According to friends, both IE 10 and IE 11 have the same isues with OpenRailwayMap.

**Comment by bigbug21** [comment]
Some more details on the non-moving ORM on IE 11. The error message reads:

*** cut ***
SCRIPT5: Zugriff verweigert
Datei: view, Zeile: 1, Spalte: 1
*** cut ***

**Comment by bigbug21** [comment]
If there is no short-term solution in sight, it might be a temporary solution to throw a simple pop-up warning for IE users, referring to Chrome and Firefox.

**Comment by bigbug21** [comment]
Since the recent Leaflet update, ORM works flawlessly on IE 11!

**Comment by rurseekatze** [comment]
:+1:
