### ISSUE TITLE
Render *.0 milestones

### ISSUE THREAD

**Issue by ghost** [rurseekatze/OpenRailwayMap#276]
The milestones with km *.0 should be handled special, in form that they are rendered even in lower zoom levels and get a better z-index.

That gives a better overview over the track, when needing finer stations, zoom in and then seeing all milestones.

Maybe to save space the label could be cropped from "76.0" to "76".

**Comment by HH882015** [comment]
Close this

**Comment by rurseekatze** [comment]
I do not like the idea to crop e.g. `76.0` to `76` because that could it make more difficult for users to identify that label as a kilometer value.
