### ISSUE TITLE
JOSM: speed sorting

### ISSUE THREAD

**Issue by ghost** [rurseekatze/OpenRailwayMap#302]
Would it not be better to sort speeds for signals like this:

off;60;50;40 (example)

instead of

off;40;50;60

That would mean the highest possible speed is left (off), then following the lower speeds in order.

**Comment by bigbug21** [comment]
Okay, but what's the actual purpose of sorting maxspeeds like this?

**Comment by PeterDRS** [comment]
They are well-formed ordered.

**Comment by bigbug21** [comment]
#306 did quite the opposite.

**Comment by DerDakon** [comment]
The rendering code can now deal with any order. Since no ordering is superior to the other and we already have one ordering I suggest to close this.
