### ISSUE TITLE
H/V Vr light signal

### ISSUE THREAD

**Issue by PeterDRS** [rurseekatze/OpenRailwayMap#312]
Currently the state DE-ESO:kennlicht is known.

Does it make sense to change it to "off"?

In this case a tool can distinguish:
* Standalone Vr light: Show Kennlicht (marker light)
* Combined main and distant signal: distant signal stays completely off

**Comment by Nakaner** [comment]
![kennlicht](https://cloud.githubusercontent.com/assets/3611273/9446922/c43b7e7a-4a94-11e5-9fb7-eaeee08f24ce.jpg)

**Comment by PeterDRS** [comment]
My list is not wrong. ;)

What you show is a standalone Vr, as there is no main signal. There is no main signal as it is disabled using the marker light, so it does not exist any longer.

**Comment by PeterDRS** [comment]
http://www.bahn-seminar.info/.cm4all/iproc.php/Kennlicht%20HV_900x650.png/downsize_1280_0/Kennlicht%20HV_900x650.png

**Comment by rurseekatze** [comment]
This issue is a tagging discussion which should be continued/restarted on the mailing list.

**Comment by PeterDRS** [comment]
BTW: Why not doing tagging discussions on GitHub? It is much more comfortable, as it is easily possible to upload images.

**Comment by bigbug21** [comment]
There is a good point in doing tagging debates in a different way. Github (or something similar) would offer a better structure. Those interested could have plenty of space here while nothing more than the opening and closing of a tagging debate would be announced on the mailing list. I doubt that the current mailing list is well-suited for a number of tagging debates at the same time.

**Comment by rurseekatze** [comment]
Github is a platform for developers to host code and discuss problems related to the code. That is not the case for tagging issues as they concern other applications, too. Or would you discuss tagging questions in the repositories of JOSM or the OSM website?

**Comment by bigbug21** [comment]
The OSM Wiki sounds like a good idea to have a number of such discussions at the same time without flooding the mailing list with a number of opinions on various issues.

**Comment by PeterDRS** [comment]
@rurseekatze It is easy for you: You are mighty with your map, you invented the buggy scheme and now you say: It wasn't me, if you want to change, try posting to mailing lists where nobody reads it and after 1 month you close the issue saying "Your proposal is bad." That's an easy world.

PS: I had lots of signals that changed from distant to main and to combined or vice versa. Every time I think why not having just one checkbox. But that's something that may not exist. It's evil!

First thing the train analysis tool does is to split combined to main and distant.

**Comment by bigbug21** [comment]
@PeterDRS: This issue is not about content, but rather about a formality. So far, the usual and commonly accepted way for tagging scheme changes is the mailing list. Feel free to post this issue their, so we can have a proper debate.

**Comment by bigbug21** [comment]
@PeterDRS: It was not just rurseekatze's "fault". The current tagging scheme is mainly based on the documented debates of the past.

**Comment by PeterDRS** [comment]
I think posting things to mailing list is senseless.

Two or three persons, who are also here on this repository, write something and then happens nothing and after a while someone says: Declined.

**Comment by PeterDRS** [comment]
> The current tagging scheme is mainly based on the documented debates of the past.

Where are the documents saying that there must be its own type "combined". I can't find them, though I looked at archived documents.

So it is not always "right" just because it exists since 2-3 years and nobody has yet said: "Think about doing it another way."

**Comment by bigbug21** [comment]
From what I can recall from our Cologne meeting in 2014, there was never really a discourse about doing Ks combined signals in a different way. As for myself, I promise to respond to the latest mailing lists posts, when there is time for that. Over and out.
