### ISSUE TITLE
Signal height

### ISSUE THREAD

**Issue by PeterDRS** [rurseekatze/OpenRailwayMap#317]
Currently the tag signal:main:height is used as normal or dwarf.

What is with extremely high narrow signals like this one here:
http://www.eisenbahn-signale.de/temp/ks01.jpg

Would it be possible to use height=high

That could indicate people looking out of the window of a train that they can hardly not see the signal out of the side window because it is higher than the train windows.

**Comment by rurseekatze** [comment]
This is a tagging discussion which does not belong to the Github repository. Please post your question on the mailing list again.
