### ISSUE TITLE
Render main signals at lower zoom levels

### ISSUE THREAD

**Issue by bigbug21** [rurseekatze/OpenRailwayMap#318]
The current signalling layer appears to be mostly empty from zoom level 13 and below. It would be good to have the most important signals (main signals) at lower zoom levels as well. 

Why not render them up to (at least) zoom level 11, perhaps without ref? This would also greatly help tp get an overview of block sections of a route, hence an a idea of those sections that might be the key to increase performance.

**Comment by PeterDRS** [comment]
Same as #304?

I don't really know when a zoom level is "higher" or "lower". I meant lower with higher I think.

When zooming out, I say "higher zoom" to it because I mixed it up with a plane, which then is "higher".

**Comment by bigbug21** [comment]
Thanks, this is indeed the same thing as #304 and can be closed.
