### ISSUE TITLE
Throw warning: Repeated and shortened

### ISSUE THREAD

**Issue by ghost** [rurseekatze/OpenRailwayMap#319]
Due to a buggy tagging scheme it is possible to tag a distant as repeated and shortened. That's of course nonsense.

It would be good to have a warning here.

**Comment by DerDakon** [comment]
At least for H/V this is possible, but detectable: https://de.wikipedia.org/wiki/Halbregelabstand

**Comment by PeterDRS** [comment]
The distant signal can be a repeater or in short distance at the same time?

**Comment by DerDakon** [comment]
It is a shortened one for Vr1 and a repeated one for Vr0.

**Comment by PeterDRS** [comment]
Which of these signals?

**Comment by DerDakon** [comment]
AN, 5, 7, 9

**Comment by PeterDRS** [comment]
No. It is only shortened. None of these are repeaters.

**Comment by PeterDRS** [comment]
Quite complicated.

Halbregelabstand destroys all logic. It is very special and ... has no future. Ks is the future.

**Comment by PeterDRS** [comment]
The problem is that H/V distants have marker lights for Vr1. If that wasn't, everything would be fine.
