### ISSUE TITLE
Improve handling of multiple signals on a single pole

### ISSUE THREAD

**Issue by bigbug21** [rurseekatze/OpenRailwayMap#354]
On quite a number of occasions, more than one signal and/ore milestone is located on the same pole. For example:

* a milestone and a speed signal on a catenary mast
* a "Blockkennzeichen" sharing a pole with a milestone
* twin lf7 speed signal (for both directions) at the same pole

The current tagging scheme would require two nodes for something that is at the very same location in reality. In a longer run, there should be some way to handle such things.

**Comment by DerDakon** [comment]
This should be discussed on the mailing list as it affects the tagging in general. Just start a discussion, I will join in with more examples ;)

**Comment by bigbug21** [comment]
I think this is rather an issue for the longer run. There are much more important issues to be covered, such as Internet Explorer compatibility. More examples can be collected right here.

**Comment by bigbug21** [comment]
(PS -- In an earlier version of this issue, there were some examples with "Blockkennzeichen" sharing a common pole with distant signals. This can already be tagged within the current tagging sheme.)

**Comment by rurseekatze** [comment]
This is a tagging discussion.

**Comment by bigbug21** [comment]
So what? I have no intention to put this up on the mailing list. This issue is a good place to keep the idea in mind and collect further examples. Could you please reopen it?

**Comment by Nakaner** [comment]
It is a tagging and mapping issue and not an issue how to use the OSM data. Therefore this is wrong place to discuss it. That's why this issued have been closed.

Tagging discussions go to the mailing list, data usage (how things get rendered and why and when) is being discussed here.

**Comment by bigbug21** [comment]
This is _not_ a discussion, but a long-term proposal that should be followed up at some point.

**Comment by rurseekatze** [comment]
@bigbug21 I understand your problem. The mailing list is good for discussions, but not for collecting long-term todos. Nevertheless this repository is not the right place for that, too. The repository contains the code of the project and all issues should be related to that.

Maybe it would be a solution to create a separate repo named e.g. "openrailwaymap-tagging" where tagging-related issues could be collected?

**Comment by bigbug21** [comment]
A (later) solution, after a debate on the mailing list (sometime), could easily relate to this issue.

There is hardly any traffic left on the mailing list. Why should another repository be created??

**Comment by bigbug21** [comment]
Rephrased and opened up again as a technical bug, rather than an enhancement. #392
