### ISSUE TITLE
Ignore maxspeed tags on abandoned and razed railways

### ISSUE THREAD

**Issue by sb12** [rurseekatze/OpenRailwayMap#37]
Hi,
abandoned and razed railways often share a way with highways. In these cases the maxspeed of the highway is shown.
Example:
http://www.openrailwaymap.org/?lang=de&lat=49.31348478032425&lon=8.453121185302734&zoom=14&style=maxspeed

**Comment by Nakaner** [comment]
This issue has already been fixed. See also issue #38.

**Comment by rurseekatze** [comment]
Merged #103.
