### ISSUE TITLE
Strange rendering artifacts

### ISSUE THREAD

**Issue by mmd-osm** [rurseekatze/OpenRailwayMap#378]
Sometimes the renderer produces some strange artifacts, like the straight line into the North Sea on the following screenshot. When zooming in or out, those lines usually disappear.

Not sure if this is a known issue.

![render](https://cloud.githubusercontent.com/assets/5842757/10558674/06b3b8bc-74d9-11e5-8630-70fb3335633e.png)

Link: http://www.openrailwaymap.org/?lang=de&lat=51.18967256411778&lon=7.448730468749999&zoom=7&style=standard

**Comment by Nakaner** [comment]
The issue is already known.

**Comment by mmd-osm** [comment]
ok, great. If you like, you can reference the existing github issue and close this one. thanks.

**Comment by rurseekatze** [comment]
See https://github.com/rurseekatze/node-tileserver/issues/11.
