### ISSUE TITLE
Deactivation cross is rendered eventhough the corresponding signal is not rendered on this zoom level

### ISSUE THREAD

**Issue by sb12** [rurseekatze/OpenRailwayMap#390]
railway:signal:crossing:deactivated=yes on zoom 14:
![untitled](https://cloud.githubusercontent.com/assets/5783139/10608809/f69c78aa-7740-11e5-8f38-dfb378bf87b3.png)
http://www.openrailwaymap.org/?lang=en&lat=49.01639738662386&lon=8.448443412780762&zoom=14&style=signals

**Comment by DerDakon** [comment]
The problem is not "zoom level". The corresponding signal would probably be rendered on this zoom level, but we currently have no way to render both the signal and the cross because we can only render one icon at a time.

**Comment by sb12** [comment]
In this case it is a crossing signal which is rendered from z15 and higher. Sorry should have mentioned that in the first post.

**Comment by DerDakon** [comment]
Like that: https://github.com/DerDakon/OpenRailwayMap/tree/crossing-deactivated?

**Comment by sb12** [comment]
Yes, I think that would solve the issue. The zoom level for shunting signals needs to be adjusted as well. There's only one such signal in the database: http://www.openrailwaymap.org/?lang=en&lat=51.899442301347946&lon=11.456744670867918&zoom=15&style=signals

**Comment by DerDakon** [comment]
Good catch, updated.
