### ISSUE TITLE
Wrong color on line endings if track ends in tunnel

### ISSUE THREAD

**Issue by DerDakon** [rurseekatze/OpenRailwayMap#417]
[Hannover Flughafen](http://www.openrailwaymap.org/canvas.php?lang=de&lat=52.45797151659682&lon=9.699051529169083&zoom=19&style=standard)
[Frankfurt Süd](http://www.openrailwaymap.org/canvas.php?lang=de&lat=50.097501059736445&lon=8.689897209405899&zoom=19&style=standard)

It becomes better visible when zooming in and out. Since I'm currently not sure if it is an error in the MapCSS definitions or in the rendering code I report it here where people will probably search first.

**Comment by rurseekatze** [comment]
Tunnels use `linejoin: butt;` while the tracks use `linejoin: round;`. That causes this rendering result.

**Comment by DerDakon** [comment]
It's linecap, not linejoin that creates the problem here. But I think it does not make sense to have linejoin:butt for tunnels, especially as it will not match with the corresponding lines.
