### ISSUE TITLE
Integrate window.postMessage for Child-To-Parent communication in legend-generator.php

### ISSUE THREAD

**Issue by grill2010** [rurseekatze/OpenRailwayMap#530]
Hi,

do you think it is possible to integrate a window.postMessage in your legend-generator.php? The reason why I'm asking is I need the real height of the generated legend inside my iframe, but due security reasons browsers don't allow direct access to the content of an iframe. So all I need (and maybe some other people) is the real height of the legend which can be published like this from you legend-generator.php:

```
window.onload = function() {
        // post our message to the parent
        window.parent.postMessage(
            // get height of the content
            document.body.scrollHeight
            // set target domain
            ,"*"
        )
    };
```

This short snippet would allow all interested websites to adjust the height of their iframes. If not it's not a big deal but I have to adjust the height manually and hard coded in relation to the zoom level at the moment which is not very optimal.  Many thanks for your help.

**Comment by DerDakon** [comment]
This works in our code in [setIframeHeight()](https://github.com/rurseekatze/OpenRailwayMap/blob/master/js/functions.js#L132), what is different in your setup?

**Comment by grill2010** [comment]
Okay, I've completly missed this. I was a bit in hurry during my last project but I've tested it now an it works. Sorry for the circumstances and thank you for your help.
