### ISSUE TITLE
openrailwaymap down -> JOSM takes forever to start

### ISSUE THREAD

**Issue by mmd-osm** [rurseekatze/OpenRailwayMap#542]
JOSM 10945 hangs during startup, as openrailwaymap.org appears to be unresponsive at the moment and the signals.zip file cannot be downloaded.

Error message:

WARNUNG: Fehler beim Laden von http://www.openrailwaymap.org/styles/signals.zip, zwischengespeicherte Datei wird bis zum nächsten Versuch verwendet: java.net.ConnectException: Die Wartezeit für die Verbindung ist abgelaufen

Any chance to host signals.zip on some other location instead to avoid this situation in the future?

**Comment by rurseekatze** [comment]
Everything except for the mailing list should work again now. I was deploying https://github.com/rurseekatze/OpenRailwayMap/pull/524 which needed some Apache configuration. Sadly there were some problems, so the downtime was longer than expected.

Normally, such a long downtime should not happen again. The only way to avoid this would be to host the *.zip files in the Github repository. But currently they are not included in the repo and build with a Makefile on the server. So I currently see no need and no possibility to host the presets somewhere else.

I expected that JOSM caches presets loaded from external resources to avoid such problems?!
