### ISSUE TITLE
No data on http://www.openrailwaymap.org/

### ISSUE THREAD

**Issue by andreasbernhard** [rurseekatze/OpenRailwayMap#567]
For several weeks http://www.openrailwaymap.org/ is without any data. Does anyone know how to help?

**Comment by Nakaner** [comment]
@openrailwaymap [wrote](https://twitter.com/openrailwaymap/status/815840280301674496) at Twitter:
> OpenRailwayMap is currently moving to a new server. There might be technical issues or temporarily downtime in the next days.

**Comment by andreasbernhard** [comment]
Thanks for getting it back online!
