### ISSUE TITLE
Add OpenRailwayMap do Taginfo projects list

### ISSUE THREAD

**Issue by endro** [rurseekatze/OpenRailwayMap#60]
http://wiki.openstreetmap.org/wiki/Taginfo/Projects

**Comment by rurseekatze** [comment]
Was fixed in https://github.com/rurseekatze/OpenRailwayMap/commit/c68756d67af7c871a5638ec03bfd8cb924ee7fa1.

This file is far away from being complete. This will need some time and work. Contributions are welcome.

The integration into https://github.com/taginfo/taginfo-projects will be done soon.
