### ISSUE TITLE
API should return XML/GML format

### ISSUE THREAD

**Issue by rurseekatze** [rurseekatze/OpenRailwayMap#7]
The API should return the data not just as JSON, but also in XML or GML format.

**Comment by mediavrog** [comment]
Is it possible to retrieve geo-information/coordinates on individual routes?

**Comment by rurseekatze** [comment]
This issue is just for discussing the possible output formats of the API.

Please add a new issue for your question, and then describe your question more detailled.

**Comment by rurseekatze** [comment]
JSON format is sufficient for our purposes. XML-based formats do not offer any advantages and are today less popular than JSON.
